services:

    database:
        container_name: garciarte-db
        image: mysql
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - garciarte-db:/var/lib/mysql
        environment:
            TZ: "${TIMEZONE}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
        networks:
            ntw:
                ipv4_address: 172.16.0.3

    php:
        container_name: garciarte-php
        build: ./php
        volumes:
            - ./../:/application
        depends_on:
            - database
        networks:
            ntw:
                ipv4_address: 172.16.0.4

    nginx:
        container_name: garciarte-nginx
        image: nginx:stable
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./../:/application
        depends_on:
            - php
        networks:
            ntw:
                ipv4_address: 172.16.0.2

volumes:
    garciarte-db:

networks:
  ntw:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.1